apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: gcr.io/_PROJECT_NAME_STG_/_DOCKER_IMAGE_NAME_:_TRAVIS_COMMIT_
        ports:
        - containerPort: 8080
